[package]
name = "recorder"
version = "0.1.0"
authors = ["Raizex <jwhuffman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gst = { package = "gstreamer", version = "0.16.7"}
